name: Markdown Lint

on:
  push:
    branches:
      - main

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: ./github/actions/checkout

      - name: Set up Node.js
        uses: ./github/actions/setup-node
        with:
          node-version: '18'

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Lint README.md
        run: markdownlint README.md
